name: Validate ICS File

on:
  push:
    paths:
      - 'whfc.ics'
  pull_request:
    paths:
      - 'whfc.ics'

jobs:
  validate-ics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install icalendar library
        run: pip install icalendar

      - name: Validate whfc.ics
        run: |
          python -c "
import sys
from icalendar import Calendar

with open('whfc.ics', 'rb') as f:
    try:
        Calendar.from_ical(f.read())
        print('✅ ICS file is valid.')
    except Exception as e:
        print('❌ Invalid ICS file:', e)
        sys.exit(1)
          "